name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: abozanona/pacman-contribution-graph@v3.2.5
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Commit and push generated SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/*.svg
          git commit -m "chore: update pacman contribution graph" || exit 0
          git push